---
title: "The Moral Privilege of True Love"
thanks: "Thanks to the ASA. **Current version**: `r format(Sys.time(), '%B %d, %Y')`; **Corresponding author**: montaque.reynolds@gmail.edu"
author:
- name: Montaque Reynolds
  affiliation: Saint Louis University
# bibliography: "`r paste0(Sys.getenv('HOME'),'/Dropbox/master.bib')`" # This would be more general
bibliography: /home/redapemusic35/data_storage/Un-Duplicates.bib
abstract: "Christine Korsgaard and Roman Altshuler respond to the reductionistic identity problem using narrative identity. On this account, we are defined by the stories we accept about ourselves. Analogously, some have held that we can determine the values an artist holds, by carefully listening to the song lyrics they write. Although this fact would suggest that an artist's lyrics might qualify as a personal narrative defining an artist's identity and agency, no attempt has been successful. According to some accounts, an artist's written lyrics and musical arrangement merely express plausible values someone might hold, others articulate them as definitive, still others argue that art is functional. Following the emotion of regret in the narrative of agency literature, I provide an account of agency rooted in lyrical expressions of regret. Such expressions may serve to help artists and their audiences, discover what that artist, or the audience, cares most about."
keywords: "Care Ethics, Aesthetics"
geometry: margin=1in
#mainfont: cochineal
#sansfont: Linux Biolinum O
fontsize: 11pt
endnote: no
always_allow_html: true
header_includes:
  - \usepackage{longtable}
  - \usepackage{hyperref}
  - \usepackage{setspace}
  - \usepackage{amsthm}
  - \usepackage{xurl}
---

```{r setup, include=FALSE}
library(dplyr)
library(magrittr)
library(tidyverse)
library(stevemisc)
library(modelsummary)
#library(huxtable)
#library(kableExtra)
#library(stringr)
library(sentimentr)

knitr::opts_chunk$set(fig.width=2, fig.height=2)

```

# Introduction

According to reductionism in personal identity, personal constitution, what defines the persistence of the human person over time, is reducible to psychological states being bound together. Causlism is the most popular account that explains the constitution of these psychological states. Accordingly to the causalist account, an object *A* at time *T$_1$* is identical to object *B* at time *T$_2$* as long as we can draw a continuous line from object *A* at time *T$_1$* to object *B* at time *T$_2$*.

Narrativists have argued that such accounts undermine our concepts of agency and moral responsibility, failing to explain attributions of praise or blame in response to an agent's actions. This is because they offer no way to define the line as beginning at *T$_1$* and ending at *T$_2$*. Christine @kors89 proposes a practical conception of narrative identity. Accordingly, an agent is a person who uses narrative to define their own constitution. She calls this the *self*-constitution model of personal identity.

# Works Cited

<!-- This option seems to be more pleasing for rmarkdown::pdf_document() with my templates -->
<!-- \setlength{\parskip}{6pt} -->

<!-- If you're using bookdown, this seems to look better with bookdown::pdf_document2() -->
\setlength{\parskip}{8pt}
\setlength{\parindent}{-0.15in}
\setlength{\leftskip}{0.15in}
\vspace*{-0.35in}
\noindent


