# Kuplen, Theraputic Self-Knowledge

> Our engagement with narrative works of art gives us a unique opportunity to adopt a dual (first-and third-person) perspective on the self ...

by

> allow[ing] us to experience both perspectives, thereby helping us make sense of our own internal experiences and to recognize the meaning of these experiences in the larger context. [@kupl20, 57]

* Factual Self-Knowledge: knowledge of our own experiences, thoughts, emotions, beliefs, desires, and other mental states that constitute the self.

* Therapeutic Self-Knowledge: , not completely new information abouut our own self; but allows us to recognize various psychological aspects of "our inner life".
  * These guide emotional experiences and behavior

## Self-Knowledge

* To have self-knowledge is to have a clear sense of who "we truly are".
  * Having a clear sense of who we are is necessary for leading a meaningful authentic life.

What does it mean to have a sense of who we are?

Having a clear sense of who we are is referenced by knowledge of our own mental states (experiences, thoughts, emotions, beliefs, desires, and other mental states) 'that constitute the self'.

There are two main sources of self-knowledge.

### 1 First-Personal Perspectives (Introspection)

* Self-Knowledge
  * Agency is defined as an aspect of first-person authority.
  * It is our acknowledgement that psychological states are our own and that we are privileged over our psychological states.
  * We can shape our psychological states in a way we find appropriate.
    * Moral deliberations, being able to deliberate on the appropriateness of our feelings
    * We feel rather than believe, that a given mental state is emotionally convincing and harmonizes with our 'patterns of feelings, thoughts, and actions'.

### 2 Third-Personal Perspectives

* Self-Perception

## Conveying information through narrative works of art

1. Narrative works of art function as "simulations of selves in the social world."
2. Each work carries a different explanation or interpretation of the issues and themes portrayed depending on the different ways of selecting, specifying, and arranging elements of the story together.
3. They give us "the opportunity to put ourselves in the shoes of fictional characters" taht mementarily inhabit our thoughts, beliefs, and feelings.
4. Therefore, they offer us an abstracted and simplified model of real-life experiences.
