---
title: "True Love's Agency"
subtitle: "God, Moral Realism and the General Affirmation of Personhood"
thanks: "There are too many people to thank given how humble this submission is. However, the *American Society of Aesthetics*, Dan Haybron, Scott Gelfand, Joshua Rust, Helen De Cruz, Jonathan Gilmore have been notable in its completion. **Current version**: `r format(Sys.time(), '%B %d, %Y')`; **Corresponding author**: Withheld for Peer Review"
author:
- name: Withheld for Peer Review
  affiliation: Stetson University
# bibliography: "`r paste0(Sys.getenv('HOME'),'/Dropbox/master.bib')`" # This would be more general
bibliography: /home/redapemusic35/data_storage/Un-Duplicates.bib
abstract: "With respect to personal identity, both Roman Altshuler and Christine Korsgaard argue we are defined by the stories we accept about ourselves. On Korsgaard’s account, we select various events from our past and weave it into our own constructed narratives, Robust Representation. For Altshuler, this account neglects the affect that some events have in the construction of our self-constitutions. I argue that if this is what narrative in the psychological sense is, then we ought to recognize them as a ubiquitous artifact in much of what we recognize as modern and popular artworks, what I call Generic Representation. Given current popular conversations regarding black representation in country music, perhaps now is a good time to talk about the importance of representation in popular music more generally. For instance, emerging work on country music standardly criticize a lack of ethnic diversity in country music. In effect, this lack of ethnic diversity erase the cultural contributions of racial and ethnic minority communities. I first make a distinction between generic and robust ethnic representation and show that generic representation is maximally corrosive to ethnic identity while robust ethnic representation is maximally formative. So while one may argue that any representation is better than none, I argue that this view ignores the complexity of representation and identity. Therefore I then develop an account of Robust representation grounded in feelings of regret. In a world that determines to undermine seeks to undermine human personhood, narratives about our relationships with others and God can help us to preserve more general accounts of personhood. As such, we should adopt Robust Representation and reject Generic Representation."
keywords: "Care Ethics, Aesthetics"
geometry: margin=1in
#mainfont: cochineal
#sansfont: Linux Biolinum O
fontsize: 11pt
endnote: no
always_allow_html: true
header_includes:
  - \usepackage{longtable}
  - \usepackage{hyperref}
  - \usepackage{setspace}
  - \usepackage{amsthm}
  - \usepackage{xurl}
format:
  pdf:
    geometry:
      - top=30mm
      - left=20mm
  html:
    code-fold: true
    html-math-method: katex
  docx: default
---

```{r setup, include=FALSE}
library(dplyr)
library(magrittr)
library(tidyverse)
library(stevemisc)
library(modelsummary)
#library(huxtable)
#library(kableExtra)
#library(stringr)
library(sentimentr)

knitr::opts_chunk$set(fig.width=2, fig.height=2)

```

# Personhood and Identity

Many popular songs are saturated in the emotion of regret.

*The Grand Tour*

> As you leave you'll see the nursery

> Oh, she left me without mercy

> Taking nothing but

> Our baby and my heart

and

*He Stopped Loving Her Today*

> He kept her picture on his wall

> Went half crazy now and then

> But he still loved her through it all

> Hoping she'd come back again

The above are emblematic country songs in that regret is commonly expressed in country music. Different songs express regret in different contexts however. *Apologize* by Timbaland is not a country song, and expresses regret in a different context. Here the narrator expresses regret for the love he *had* felt.

> You tell me that you need me

> Then you go and cut me down, but wait

> You tell me that you're sorry

> Didn't think I'd turn around and say

Love songs often express regret when a relationship ends. In the song *The Grand Tour*, the audience is being asked to imagine an offer to tour a large home "step right up, come on in". It is eventually made clear that while there are evidences as to whether the home is lived in, and by whom, these items are no longer in daily use "where she used to . . .". While the artifacts themselves speak to the fact that they were once shared by people who expressed positive sentiments towards one another, their current state suggests that they are no longer used this way ". . . this old house will never be the same . . .". In *The Grand Tour*, there is existing controversy over whether the end of the relationship is caused by the narrator, or the person no longer there. In the podcast *Cocaine and Rhinestones: The history of country music*, Tyler Mahan Coe suggests that the change in the state of the lives of the individuals involved in the story, is the result of a tragic mishap "There's her rings, all her things, and her clothes are in the closet" and "as you leave you'll see the nursery, . . . taking nothing but the baby and my heart".

While the events in *The Grand Tour* may not have been caused by the involvement from any agent, regret more often is tied to the involvement of some agent. In other words, the regret in *The Grand Tour* is likely caused by an event, whereas in other songs, it is likely caused by an action. In Jones' other song *He Stopped Loving Her Today*, the regret is more definitively caused by an action. "He said I'll love you 'till I die, She told him 'you'll forget in time'".

While in the two previous examples, regret is expressed upon the end of a relationship. In other examples, more positive emotions are expressed upon the dissolution of the relationship than of its continuation. For instance Kelly Clarkson's *Since U Been Gone* does this "Since you've been gone, I can breath for the first time . . .". There are also different reasons for the regret whether expressed for having suffered through the ordeal of that relationship, or for its end. Sometimes the regret is expressed as a longing for various qualities the loved possessed, for instance in the *Grand Tour*, "over there, sits the chair ... and whisper 'oh I love you'". Narrative can help us to feel closeness and union with those we love, whether or not we have met them [@stum10. In his *De Musica*, Augustine may be taken as making a similar claim when speaking of knowledge of his grandfather whom he has never met and his father whom he has.] This correlates with attributions of emotions associated with love, where love has often been defined as the feeling of loving emotions provoked in the lover by the loved. Upon the loved one's absence, the lover no longer feels these emotions and experiences regret on account of their absence [@tayl76]. The lover can also experience regret in longing for the qualities not possessed by the loved, when someone whom they loved, failed to reciprocate in word or deed failed in some other way.

Narrative accounts of agency attempt to use the way an individual responds to such events, to identify the agent through space and time. According to some narrative accounts of agency, how we frame events such as these, is what makes the event meaningful [@sche96b, 96] for a given individual. Without narratives, the agency and the identity of the subject is lost among a causal chain among random events. This has been called 'constitution'. In terms of the constitution model of agency, the subject of a given event, without the binding effect a narrative, is victim to a disparate causal chain of cause and effect, our identity is merely an impersonal metaphysical continuation of matter [@kors96]. We are then merely a random collection of atoms.

In explaining the metaphysical continuity of an object across space and time as a person, how we ought to understand what we are, Derek @parf87 defends an account of *personal* identity. In order to understand what sort of object a person is, Parfit argues we need to understand two different qualities, the nature of a person, and their *criterion of identity*, which is their continued existence over time. But when we consider these qualities in contrast to persons versus non-persons, we must include not only physical states of matter, but also immaterial ones such as mental states, memories, beliefs, motivations, etc.

While Parfit's account does show how persons are not mere matter, he and other causalists state that an action performed by an agent, is an event caused by the mental state of that agent [@alts21]. The difficulty arises in understanding how mental states are related to related to prior events. While a mental state may be the source of some event, another event may be the source of that mental state. Regardless of the relationship between mental states and the material universe, it is not clear where the causal chains originated.

Narrative accounts of personhood are based on attributed meaning to events in one's past. The meanings that stories provide are not derived from the individual meanings of the events they represent. Rather, the individual events derive their meaning from the overall meaning of the story. The outcome of the story determines the meaning of the events within the story. Why something happened is explained by the end of the story in which it happened. But this is ascribed by whoever that stakeholder happens to be. Causalists state that an action performed by an agent, is an event caused by the mental state of that agent [@alts21]. The difficulty arises in understanding how mental states are related to events, whether emotional, causal or something else.

Reductionists such as Parfit can define personal identity as the persistence of the human person over time, and say that this is reducible to the binding of psychological states with physical matter. Causlism is the most popular account that explains the origin of psychological states, an object *A* at time *T$_1$* is identical to object *B* at time *T$_2$* as long as we can draw a continuous line from object *A* at time *T$_1$* to object *B* at time *T$_2$*. The continuous line here is most often mental states such as memory, passions, character traits and dispositions. But often times it is the case that those memories we accept as definitive, have their origins in persons or events other than ourselves. There are certain dispositions I have because of persons other than myself signing various documents articulating what rights I recognize as belonging to me for instance.

In response, Christine @kors89 has argued that on @parf87's account of identity, a person is primarily a *locus of experience* [@kors89, 103]. This means that the way to identify an object as existing through space and time as it correlates with a person, is by identifying a set of experiences between objects across space and time and as are connected through a set of events or some other connecting factor. These events are psychological states and 'spatiotemporally continuous living bod[ies]' [@kors89, 104]. In this way, it is plausible to draw a line from events in 1776 to my present day. In other words, because a person's psychological states have prior causes, the states themselves are merely some form of event and experience.

The divergence not only has implications for ways in which to identify material objects persisting across space and time, but also with respect to moral attributions of praise and blame which uniquely belong to immaterial objects. For instance, Kantians and Utilitarians have differing conceptions of agency which together represent a source of justification for either view. Utilitarians too account for agency as a form of experience. When concerning moral obligation and duty for instance, it is the moral agent who deserves to be praised or blamed. In this way then, say my acceptance of a person's human rights has nothing to do with me. As such, the utilitarian asks 'what should be done for them?', persons with a characteristic form of experience. Since the Kantian asks 'what ought they do?', despite a given experience, Parfit's account does not account for what we all might think of as the exercise of agency. As such, Korsgaard goes on to argue that focusing on what an agent does, rather than their experiences, will lead to a drastically different concept of identity, grounded in a unique characterization of agency. One which she calls 'practical'. Her own account of agency and identity then, is practical.

Korsgaard then, defends a concept of narrative agency. Reductionist and causalist conceptions of agency undermine what we think of as agency with regard to moral responsibility. These accounts fail to explain the attribution of praise or blame in response to an agent's actions. This is because they offer no way to define the line as beginning at *T$_1$* and ending at *T$_2$*, in other words, the object, that persistent thing deserving of either moral praise or blame, is indefinable. @kors89 proposes a practical conception of narrative identity. Accordingly, a person is an agent who uses narrative to define their own constitution. She calls this the *self*-constitution model of personal identity. As such, Korsgaard defends an account of personhood and identity grounded in narrative agency. On this account, we are defined by the stories we accept about ourselves. The act of acceptance means that we select individual events from our pasts in order to construct a narrative that defines our identity.

The locus of the reduction is hard to pin down in the context of the kinds of desires expressed by an entity as complex as a human person. An analogous complexity can be found in many popular love songs. Although a murky concept, narratives offer a promising way to better understand causal and psychological reductionism. This is because they can incorporate and give shape to "a wide range of heterogeneous" mental states and events [@alts21] in the same manner as psychological narratives. By giving shape to these factors, narrative theories explicate an agent's motivations as a response to environmental effects.

Narrative explanations provide one account by explaining the relationship of cause and event in a way that preserves agency. Stories make our lives intelligible [@vell03] by providing motive and context to a collection of events and episodes. In other words, narrative gives meaning to otherwise meaningless events. Overall, the meanings that stories provide are not derived from the individual meanings of the events they represent. Rather, the individual events derive their meaning from the overall meaning of the story. The outcome of the story determines the meaning of the events within the story. Finally, the meaning of the outcome is determined by the story teller. Why something happened is explained by the end of the story in which it happened.

Altshuler identifies a problem with this account, namely that it does not account for those events that are not selected by the agent. He argues that such events do have a causal effects on what ultimately constitutes one's identity. Following Peter @gold09, Altshuler instead identifies narrative with an agent's *ability* to reconfigure their motivational and psychological past with respect to their own reactions to these events. In other words, Altshuler too, defends a self-constitution model of agency and identity, but one on which a person's responses to his or her past, shape her future identity.

Altshuler responds to the reductionistic identity problem by expanding Korsgaard's analysis. On his account then, we are defined by the stories we accept about ourselves, which is determined by our reflexive rather than reflective endorsements. This reflexive endorsement is determined by emotions we express upon our reflection on our narratives. Since on Altshuler's account, it is possible for the agent to give an accounting for all of the experiences she has by the way of reflexive endorsement or rejection, this account does not disregard important agent forming experiences. Therefore, his account is grounded in a more comprehensive description of how the agent goes about selecting events that self-prescribe their identity.

Although narrative offers promise, it is also not clear how we might recognize a narrative in the wild, what does a sample narrative look like? Focusing on the expressions of regret in some popular songs may provide one answer. If some songs are narratives, the expressions of regret in them, may provide a response to psychological and causal reductionism. Love songs or anti-love songs can express regret for when the relationship ends, or regret for the relationship not ending sooner; which is another way for thinking about how the narrator's life may have gone differently. What is important about the expression of the feeling of regret here, is what that experience does for the agent's behavior going forward in the context of the meaning that the narrative gives to that event, or the agent derives from it. Love songs could be a form of narrative thinking in both the philosophical context and the popular one. Importantly here however, love songs might be a process by which someone organizes their experience and creates their own identity [@sche96b].

## Rap, Hip-Hop, and Other Popular Music Forms

It is possible that when a song expresses regret for not having met someone sooner, they are thinking about how their life might have gone had they married sooner. The marriage itself is not meaningful for the individual as a stand-alone event. Rather, the marriage only has causal influence on the subsequent events of that person's life and it is the person who defines the event in such a way to make it a meaningful marker of their own identity. It is where the marriage sits in the overall context of the course of a given relationship for instance. A marriage event in the context of a short and harmful relationship has a very different meaning than one in the context of a long and loving relationship. Most importantly however, it is important in the context of the meaning that a person derives from the event. The context of expressed regret best explains this.

Peter Goldie highlights our emotions as a form of reflection, especially that of regret. Sometimes as agents, the expressions of regret enables one to better exercise their own agency. We can imagine someone being cheated through the purchase of a used car. Looking towards the future, that individual would exercise more caution as a consequence upon reflection of their mistake. In these moments, the ability to tell a story becomes important as we are enabled by the narrative to recognize the appropriate objects of our emotions in the story. Reflecting on the failed used car purchase, the subject experiences regret. This subsequent experience pushes them to exercise more caution in the future. Similarly, we can compare this to another example. Here, regret is either appropriate to aspects of the story which bear no direct relation to the narrator, or ones that do. Being able to recognize and reflect on emotions enables one to express their agency going forward. What regret is afforded to the subject when reflecting on decisions made by themselves?

Michael @brat00 argues that as agents, we are purposeful and reflective about our motivations, and capable of organizing our activity over and in-line with our purposes and motivations as we reflect on them. One method of reflection involves the expressions of various emotions upon the occurrence of some event.

In his paper *Narrative Thinking, Emotion, and Planning*, Peter Goldie provides a possible way to combine moral psychology and normative theory. He argues that narrative is substantial in our lives as it provides ways of thinking about how our lives may have gone differently, or may go differently and why; our plans for the future and how things might turn out.^[For contrast, see Michael @brat00 argues that as agents, we are purposeful and reflective about our motivations, and capable of organizing our activity over and in-line with our purposes and motivations as we reflect on them. One method of reflection involves the expressions of various emotions upon the occurrence of some event.] Thinking in this way leads to regret if we are disappointed in a particular choice we have made. Our feelings of regret can cause us to behave differently in the future. In part then, questions about narrative thinking may be questions about moral agency.

Importantly, the possible prospect of being able to imagine today what a morally good life will look like for us tomorrow, is a question about how what we believe about ourselves today, including what desires we have, influence our ability to pursue these ways of being. These in turn determine our regrets. Imagining what kind of person our spouse will be can perhaps open up some romantic possibilities while closing others. Imagining where we will buy our first home may restrict our career choices, just like imagining how many children we will have may affect where we want to live. But more importantly, having various beliefs about ourselves undergird all these other possibilities.

More importantly, we can develop a sense of agency when we imagine ways in which our friendships, family ties, and other important relationships will go, which is preceded by beliefs in us about ways they *could* go. We can imagine the type of person we are to others and take needed steps for becoming that person, if we believe it is possible. As such, the person we will be and how we will relate to others is the goal that is formed by a narrative. Consider one particular narrative, we imagine ourselves as thoughtful, kind, considerate, loving, or compassionate. Imagining ourselves this way becomes the motivation we need to read up on the latest parenting methods. We might imagine ourselves being invited to witness the birth of a friend's first child and scour the internet for advice on how to be a better gift giver.

While the argument that the way we imagine our lives going can have a positive causal effect on the kind of person we become, one may argue that this view is too optimistic. To what extent do the experiences we have, shape the person we become? For instance, Eric J. @mill20 argues that victimhood imposes normative standards that ground the moral status of the victim. What he means is that social roles, such as victim, determine the values we are expected to live by. As a victim, there are various normative standards imposed on us that undermine our ability to imagine other parenting styles and values, such as those relating to how we protect and nourish our children. Libertarian values may be those we are less apt to promote in our homes. One reason is that when victims as parents, or the parents of victims, instruct a child, they must instruct them to act in self-subordinating ways "when confronted by the police" [221] rather than in ways that assert their autonomy.

Consider the following example narratives:

* Ty Dolla’s *by Yourself*: “Stacked your bread and bought your own Mercedes (Vroom, vroom). You your own boss, do it your way (Way)

And contrast this with the possibility that while material goods may or may not be a necessary condition for well-being, they are certainly not a sufficient one as expressed in other popular songs. The protagonist in the song *Rich and Sad* by Post Malone, looks back over the events, motives, and desires that resulted in the dissolution of his relationship and he feels sadness, as an expression of regret:

* “All this stuntin' couldn't satisfy my soul (–oul), Got a hundred big places, but I'm still alone (–one)”.

First, each of the above narratives are constrained by beliefs the narrator may have about themselves. In the first, the narrator, believing they have no other choice but to cut themselves off from anyone who is unable to contribute financially. But it does lead to another criticism, the agency of the artist versus that of the audience. Some music criticisms will often point out that musical taste assumes a sense of moral autonomy not available to some. If an artist is accustomed to abject poverty, then that person might be seen as vulnerable to market forces, creating art that is in high demand for the purposes of financial gain [@layb18], or only capable of representing their immediate physical environment [@rich02]. Regret within narratives are an example of such narrative agency. But if Eric Miller is correct, then some populations just do not possess agency in the requisite sense. But this view would thoroughly undermine decades of social justice movements in law and elsewhere.

What I mean by objects, are representations which are mimetic in nature. The common responses to such criticisms come in two forms. They typically make some causal claim about the effects of environment on both artistic performance [@rich02], and audience music selection criteria, for instance, that artists are merely defining their personal experiences [@shus07, 419]. This response will highlight unequal wealth opportunities among US social groups which would suggest the creation of environments of distrust and hopelessness and lower life expectancies which some rap and hip-hop songs are merely reporting on. The second kind of response makes a cultural claim deriving from supposed traditional practices in pre-colonial Africa [@abra06].

Importantly here, the responses that are grounded in assertions about the culture of pre-colonial Africa are not necessarily a response to the empirical claims about the representations of anti-social behavior in rap and hip-hop music, but rather to the metaphorical use of language exhibited by pre-colonial African tribal practices. What are commonly noted as anti-social themes in rap and hip-hop, then are downplayed as word-play underlying a cultural or political critique or something else entirely. Namely the references to violence and misogyny are allegorical, not literal [@smit97; @gate89]. What is important among these responses, is that they too undermine attributions of personal identity and human agency.

Separately, some have held that we can determine the values an artist holds, by carefully listening to the song lyrics they write. Although this fact would suggest that an artist's lyrics might qualify as a personal narrative defining an artist's identity and agency, it is not clear whether such narratives would qualify on this account of narrative agency. Although Altshuler's account could give more credence to music lyrics as an example narrative in the psychological sense, it is not clear how this may be the case. According to some accounts, an artist's written lyrics and musical arrangement merely express plausible values someone might hold [@malo18], while others articulate them as more definitive [@meis22a], still others argue that art is functional [@gilm20], thereby leaving open the possibility they could count as narrative in the functional sense, but do not do so necessarily.

It may be that rap and hip-hop are not good example narratives. But they show promise. Consider the question above, is some material good a necessary and sufficient condition for well-being as expressed in some popular songs? As narratives, the two examples above would better explain why some event happened. Why the protagonist in *by yourself* severed their relationship with their significant other, and why the protagonist in *Rich and Sad* is rich and sad.

Here, we primarily contrast [money] as the material object expressing that it:

* “could satisfy my soul”

And contrasting this with [money] as the material object expressing that it:

* “could not satisfy my soul”.

One way that narratives are thought to explain agency then, is by synchronizing incongruous events, states, and motives. As such, a narrative can say yes, money is either a necessary and sufficient condition for well-being for some agent or not. As such, the expressions of regret offers a plausible way to recognize the core of one's agency.

Therefore, recognizing the form of some plausible narratives may help to understand how to recognize a narrative if we say it. The various incidents and events have made it difficult for the agent to recognize value in non-material objects. We can, and often do, ask a meta-ethical question about what kinds of objects are truly of moral value and why. The narrative provides us with a plausible account of the why. For instance, we can ask to what extent the quest for consumer goods ought to outweigh other pursuits such as time with one's children or calling one's mother on Sunday. What is probably missing from the above is the understanding that there is a difference between only some material possession being necessary for well-being, versus some non-material possession being necessary for well-being.

But exactly how are material and non-material objects expressed over and against one another other? It may be the case that volunteering at an orphanage is of moral value and it can be expressed in song in at least two ways. Lyrically, "I wish I had volunteered at the orphanage yesterday". Or lyrically that expresses a negative outcome for not having volunteered at the orphanage yesterday. In constructing lyrics of the second form, the author chooses words that either have been historically encoded with the sentiment she is hoping to ascribe to a state of affairs, or is potentially encoded with that sentiment in such a way that the desired emotion is potentially ascribed to that state of affairs. However, if I neglect my children in volunteering at an orphanage, then *my* volunteering is of reduced moral value and we could imagine a lyrics saying "I wish I had spent time with my children instead of volunteering at the orphanage yesterday", or that says "I spent so many hours at the orphanage that I do not know who my own children are anymore"; or "I spent hours at the orphanage, I do not know who my own children are anymore".

We can also express a normative question about what behaviors are appropriate, when we should be kind, or whether a given action is more kind than another using similar methods. But there are additional interesting questions. As inferred above, we ask about the context in which a given ethical question is of moral value, and we can express it as a value by inviting the audience to reflect on such expressions by coercing their emotions accordingly. Volunteering my time at an orphanage is of moral value, and so I would use music or poetry to evoke emotions in the audience that correspond with this value. Considering the context is a way to assess the rationality of a given question, emotional expression in art is a way to make sense of that question. Making sense of the question helps us to anticipate the answer in at least two ways, what does the artist suggest is valuable, we would then look at the emotional expressions in her art, and what is the agent potentially capable of valuing.

For instance, assuming that Jill is the last sentient creature on a far away planet, it may not make sense to ask what Jill's ethical obligations are to those around her. But contexts regarding ethical questions are important. There are two important such contexts here; socio-economic or cultural environments, and psychological or social ones. Given questions about morality, our concerns are largely about how we should behave toward others. For many years, this was answered by referencing cultural and socio-economic conditions. More controversially, it has also been answered by referencing psychological or social conditions. But this is not the same as asking whether a given question about ethical obligation makes sense or not. It would not make sense to say a person with a medical condition that precludes the experience of empathy, has an ethical obligation to experience the emotions that align with empathy. There is a way in which our questions about moral behavior should make sense. This is in the context of our behavior toward others. Most humans, will generally live in contexts wherein our behavior to others should have a kind of rationality about them, in valuing our relationships with others.

The social version of this question is more opaque. It is a question about our social environments and to what extent our social environments can provide us with the resources necessary to fulfill our moral obligations. Once again, there are two categories of question here. For instance, consider our choices as to what kind of careers would make fulfilling our moral obligations possible. If we recognize a moral obligation to give vast amounts of wealth to charity, then we could pursue a set of social connections (work hard in high school and get into a good university) that would make our ability to fulfill this obligation more likely. The other category of question is even more difficult however. It begins as a question about ourselves and the sources of our beliefs as to what is possible, and what is not. We would start with a question about what is true about ourselves. Related to this is a question about what extent do those around us contribute to our beliefs about what is true about ourselves and what is obligatory in regard to our behavior. If we consider that we have a moral obligation to support national health, then there are some political parties we might campaign on behalf of and others we would not. Some philosophers have argued that how we should understand such questions is in the form of a narrative.

# Works Cited

<!-- This option seems to be more pleasing for rmarkdown::pdf_document() with my templates -->
<!-- \setlength{\parskip}{6pt} -->

<!-- If you're using bookdown, this seems to look better with bookdown::pdf_document2() -->
\setlength{\parskip}{8pt}
\setlength{\parindent}{-0.15in}
\setlength{\leftskip}{0.15in}
\vspace*{-0.35in}
\noindent


