---
title: "Christian Hip-Hop and Moral Priviledge"
thanks: "Thanks be to the ASA. **Current version**: `r format(Sys.time(), '%B %d, %Y')`; **Corresponding author**: montaque.reynolds@slu.edu."
author:
- name: Montaque Reynolds
  affiliation: Saint Louis University
# bibliography: "`r paste0(Sys.getenv('HOME'),'/Dropbox/master.bib')`" # This would be more general
bibliography: /home/mreynolds/my-lib.bib
abstract: "Narrative thinking is substantial in our lives as it provides ways of thinking about how our lives may have gone differently, our plans for the future, and how things might turn out (non-actual episodes). Looking at Christian Hip-Hop, I argue that it defines an alternative narrative. I argue that it is a moral technology that has ethical implications in a cultural context."
keywords: "Care Ethics, Aesthetics"
#geometry: margin=1in
#mainfont: cochineal
#sansfont: Linux Biolinum O
#fontsize: 11pt
#endnote: no
# pandocparas: TRUE
sansitup: FALSE
params:
  anonymous: ""
  removetitleabstract: ""
anonymous: "`r params$anonymous`"
#doublespacing: "`r params$doublespacing`"
removetitleabstract: "`r params$removetitleabstract`"
always_allow_html: true
header-includes:
  - \usepackage{longtable}
  - \usepackage{hyperref}
  - \usepackage{setspace}
  - \usepackage{amsthm}
  - \newtheorem{theorem}{hyp}
  - \newtheorem{lemma}{Lemma}
  - \newtheorem{theoremc}{Continuity}
  - \newtheorem{theoremdc}{Discontinuity}
  - \newtheorem{theoremcr}{Contextual Reasons}
  - \newtheorem{theoremfr}{Functioned Reasons}
  - \newtheorem{theoremfe}{Framing Effects}
---

```{r setup, include=FALSE}
is_docx <- knitr::pandoc_to("docx")
is_latex <- knitr::pandoc_to("latex")

# I don't know how Texas Instruments smart this is, but p-sure default DPI is 96.
# That's not a problem for LaTeX, but it looks not-so-great for Word.
# For Word, let's up that to 600. This should allow for cross-referencing
# in {bookdown} while allowing for conditional DPI

if (is_latex) {
  conditional_dpi <- 96
  return(conditional_dpi)
} else {
  conditional_dpi <- 600
  return(conditional_dpi)
}


knitr::opts_chunk$set(echo = FALSE,
                      message=FALSE, warning=FALSE,
                      fig.path='doc/figs/',
                      cache.path = 'doc/_cache/',
                      fig.width = 8.5, dpi = conditional_dpi,
                      fig.process = function(x) {
                      x2 = sub('-\\d+([.][a-z]+)$', '\\1', x)
                      if (file.rename(x, x2)) x2 else x
                      })
library(dplyr)
library(magrittr)
library(tidyverse)
library(stevemisc)
library(modelsummary)
#library(huxtable)
#library(kableExtra)
#library(stringr)
library(sentimentr)

allrds <- list.files(pattern = ".rds", path = "data") %>%
  stringr::str_remove(., ".rds")

for(i in allrds) {
      filepath <- file.path(paste0("data/",i,".rds"))
      assign(i, readRDS(filepath))
    }

knitr::opts_chunk$set(fig.width=2, fig.height=2)

```

# Introduction

Discussions on commercial hip-hop music have often taken for granted that themes in hip-hop are either synonymous with issues of social justice [@rose94; @shus07], or misogyny [For instance see @kist10c; @ande03; @john95]. Further, it is an open and controversial question whether or not the values of the communities hip-hop are said to represent are in fact represented by hip-hip artists and their music [@shus07; @shus95; @ruth01; @layb18]. Hip-hop's themes of social justice in hip-hop is often referenced as a response to historical and contemporary factors, such as mass incarceration, over / under policing, and the life expectancies of communities often associated with hip-hop. In cases such as these, hip-hop is important because of its social commentary [@nzin18a]. While it may be argued that the commercialized themes of misogyny undermine those of social justice, critics typically point out that what may appear to be misogynistic are likely critical word play. Instead, critics argue that the latter themes are either clever social commentaries in themselves, or that profit is the primary motivation for the latter themes.

The meaning and associations of these themes are often subjects for intense debates from which which there is not much hope for agreement. Here, I will consider a class of hip-hop artists that do not receive enough attention. I will analyze this class of hip-hop from within the context of a narrative response to reductionism. Here, Christian hip-hop is a narrative which introduces a practical identity [@kors89] that offers reasons for action [See @gold08; @vell05; @alth22].

# Literature Review

According to narrativists, narratives are an important function for explaining an agent's motivation to perform some action. One implication of this view then, is that agency requires one to be able to determine her own narratives.

> In understanding ourselves and others, we do so through narratives that explain the meaning of actions by specifying what motives could make sense of both the action and the various psychological, physiological, and social events that preceded it. [@alth22, 10]

In his paper *Narrative Thinking, Emotion, and Planning*, Goldie argues that narrative is substantial in our lives as it provides ways of thinking about how our lives may have gone differently, our plans for the future, and how things might turn out (non-actual episodes).

Christine Korsgaard offers a particular reason why this is an important point for practical deliberation. Narratives give us ways to think about ourselves. Who we take ourselves to be, is a fundamental factor from the standpoint of practical reason.

## Narrative Thinking, Planning, and Agency

When we make plans for the future, our actions are often constrained. We are constrained by facts about ourselves, for instance, we may not be tall enough to go on a given amusement park ride. Or have the necessary professional qualifications for a given job on the coast. Sometimes we are constrained by contingent facts about ourselves. These can include our personalities, our character traits, our emotional health and professional dispositions such as being organized or a "careful" thinker. Each of these constraints open up particular opportunities to us while blocking other ones. We can be motivated towards one course of action while being discouraged from another. Some times these constraints are external. They may be past events, for instance if we were permanently injured in an automobile accident; they could be current events, the economy and inflation making a vacation this year impossible. They can be others, as when someone rear-ends us and we become unable to go on a planned ski trip due to our injuries. We can also be constrained by the plans that others may have for us, for instance considering that our spouse may have always wanted to live near her family and therefore we decline a job offer that would make this impossible. Sometimes they are policies that others live by. Maybe our parents would never approve of us marrying someone of a different faith.

Goldie argues that past experiences can motivate counterfactual ways of thinking and regret. We may have shown up late to a job interview undermining any chance we had of working for that company. Although there are times when the constraints and experiences and the regrets they lead to are real, occurring and constraining our choices in real-life, Goldie argues that there are also times wherein they take place in make-believe and other fictional events, or counterfactual and non-local events.

Non-actual events are ones that take place in the past or in the future. It can be a part of a fiction, or some event that occurred in make-believe. Imagine a friend playing a prank on you. He tells you that there is a speed-trap set up by the local law enforcement on the way you normally take home from work. You would rather not have to worry about receiving a potential citation. There is one other route of travel available to you although this one takes on average twenty-five minutes longer. A narrative is a representation of a sequence of events and your friend has recounted a narrative to you. We become motivated to take the alternative route in order to avoid the speed trap.

More specifically, your friend's narrative is the mental representation of a sequence of events, whether in thought only, or in real life. The narrative provides coherence of the causal and other connections between events into a narrative episode or episodes. What we can glean from these episodes are coherence, meaningfulness, and emotional importance/import. Emotional importance of the narrative, Goldie calls emplotment. Emplotment is a psychological process which can be more or less successful. Emplotment can happen to those implicated in the narrative, and also those who engage with the narrative. In other words, narratives give those who are implicated by them and those who engage with them, ways to consciously or subconsciously think about the events mentally represented by that narrative.

The story your friend has told you can come with some emotional baggage. This emotional baggage, in part, is what determines the appropriateness of your response, whether you will take your usual way, or the other. Assuming that being cited for a traffic violation equates to what most of us think of as a negatively valenced experience, taking the longer route would be the appropriate response in this situation.

## II. Emotional Import

But when we think about this emotional import, it is not clear initially. First, the proper response to a situation is outlined by the emotional response to a given event. But often times, it is the narrative that outlines the proper emotional response. Our friend may say to us; "oh man, you don't wanna go that way let me tell you . . .", at which point he spins a yarn about narrowly being stopped and how if it wasn't for the guy behind him . . . etc. As such

1. Narratives first seem to outline the proper emotional response to a given event.

But, they are also,

2. distinct from emotions that are an agent’s response to a given event or sequence of events.

> The emotional import of a narrative is thus distinct from any emotion that might be felt in response: what happened was horrifying, and I, as “external narrator,” might or might not respond with horror to my horrifying narrative of what happened. [@gold08]

The distinction then is between emotional import and emotional response. We ought to contrast these two features.

1. emotional import is an integral part of the narrative

2. emotional response is a response to it

We may have felt the fear in our friend's voice. We saw him tremor as he walked in the door. But while he tells the story, if he is even somewhat adequate at doing so, it is us who feels the fear. We are transplanted into the story where as the character, we become afraid.

As the internal character, it is I *in the narrative* who feels the emotion of fear. I respond the way someone who is afraid would in the narrative, because in the narrative I find the incident to be frightening. As an external narrator, I might also feel fear as a result of conceiving this frightening incident, but the fear is not a necessary response. In the movie *Pulp Fiction*, while Vincent feels fear having just accidentally killed Marvin, we as the external character feel shock and confusion. Therefore this kind of response is external to the narrative. Therefore, the agent as audience feels shock and as character feel fear.

##### 2 Second example, where they differ

The agent as character may be humiliated by a more senior member at work. In the moment, all they would feel is humiliation, embarrassment, and shame. However, taking an external perspective on what happened, “I might conceive of what happened as deserving anger and resentment.”

By thinking through these narratives, we make the emotions appropriate in response to the narrative. For instance, dramatic irony, the narrator is not aware of crucial facts about what happened until later and as such, the external emotion, the one in response to the internal emotion is different from the internal one.

##### 3 third example, variances

- content of the thought-through narrative varies

- as does one’s grasp of what is happening in the actual world varies

Imagine a narrative scenario that explains current events. You might have heard on the news that holiday spending is down from this time last year. You can imagine that recent inflation may be the reason, or you may imagine that a recently elected politician is. A similar example may be that you are waiting for someone who has failed to arrive at the agreed upon time. You might be waiting at the train station for someone who should be there, but who has not yet shown up. You imagine her lying injured somewhere, or deciding at the last minute to make other plans.

Each imagined scenario comes complete with its own set of emotions, frustration, fear, compassion, etc.

## Narrative Thinking and Planning

When we imagine who we want to be, we may begin by thinking of what steps we can actively take to become that person. However, sometimes, once we set out on a path to becoming the person we desire, external constraints can reveal to us the feasibility of our goals. Upon entering university, we may have thought that we wanted a career in computer science but realizing how difficult the math is, we may think it is not worth it. Other factors can also constrain our choices.

Even better examples however, will concern our abilities to have close meaningful relationships with others. For instance, we may desire to be the sort of person whose "door is always open". We might see ourselves as someone who others seek out for advice, or companionship. However, we can further imagine that our financial situations makes the thought of inviting others over too uncomfortable. We may think that our house is too small or our neighborhood too impoverished, rural or dangerous.

There are two kinds of factors, positive and negative ones. A negative constraint is one wherein we pursue computer science but struggle with the math and decide we would rather study philosophy. A positive constraint however, is one wherein while we may be okay doing the math required by the CS field, it would detract too much from what we really liked about CS which is the analytic structure of argument. What we liked in computer science however, was logic and not so much the math. This is an example of a positive constraint. We discover some additional desire that we have and this constrains our choice. The positive constraint reveals an emerging goal or desire. This emerging goal or desire presents new steps that we should take.

> “Hypothetical imperatives are imperatives that tell you what you ought to do if you want to achieve some stated goal; as Kant puts it, they “declare a possible action to be practically necessary as a means to the attainment of something else that one wills (or that one may will). [@gold09, 100]

The steps here being referenced are hypotheticals, they are imperatives about what we should do given our stated goals. While hypotheticals are implied by positive constraints, there is not initially a similar object with respect to negative constraints. For instance, we may think that negative constraints are associated not with *oughts*, but with *ought-nots*, but it is not clear.

- Hypotheticals == imperatives about oughts in light of stated goals

- When you fall short of these goals, you experience negative emotions.

- the negative emotions motivate counterfactual thinking, thinking back to the crucial moment that contributed to your failure to realize your goals

- Regret is an external emotion that arises in response to your decision underlying your goal failure

- Each, negative emotions, counterfactual narrative thinking, and regrets can have a feedback effect on one’s grasp of the related hypothetical imperatives, helping one to learn from one’s mistakes.

# Works Cited

<!-- This option seems to be more pleasing for rmarkdown::pdf_document() with my templates -->
<!-- \setlength{\parskip}{6pt} -->

<!-- If you're using bookdown, this seems to look better with bookdown::pdf_document2() -->
\setlength{\parskip}{8pt}
\setlength{\parindent}{-0.15in}
\setlength{\leftskip}{0.15in}
\vspace*{-0.35in}
\noindent
\singlespacing
