---
title: "Perceiving Beauty"
subtitle: "An Augustinian Account of Narrative Planning"
thanks: "Thanks to the ASA. **Current version**: `r format(Sys.time(), '%B %d, %Y')`; **Corresponding author**: montaque.reynolds@gmail.edu"
author:
- name: Montaque Reynolds
  affiliation: Saint Louis University
# bibliography: "`r paste0(Sys.getenv('HOME'),'/Dropbox/master.bib')`" # This would be more general
bibliography: /home/redapemusic35/data_storage/Un-Duplicates.bib
abstract: "With respect to personal identity, both Roman Altshuler and Christine Korsgaard argue we are defined by the stories we accept about ourselves. On Korsgaard's account, we select various events from our past and weave it into our own constructed narratives. For Altshuler, this account neglects the affect that some events have in the construction of our self-constitutions. He argues in response to Korsgaard that our self-constitutions are determined by our reflexive endorsements upon reflection of all the events in our past. This reflexive endorsement is determined by the emotions the agent expresses upon reflection on their own narrative. Therefore, his account is grounded in a more comprehensive description of how the agent goes about selecting narratives in a way that does not discard events. I argue that if this is what narrative in the psychological sense is, then we ought recognize them as a ubiquitous artifact in much of what we recognize as modern and popular artworks."
keywords: "Care Ethics, Aesthetics"
geometry: margin=1in
#mainfont: cochineal
#sansfont: Linux Biolinum O
fontsize: 11pt
endnote: no
always_allow_html: true
header_includes:
  - \usepackage{longtable}
  - \usepackage{hyperref}
  - \usepackage{setspace}
  - \usepackage{amsthm}
  - \usepackage{xurl}
format:
  pdf:
    geometry:
      - top=30mm
      - left=20mm
  html:
    code-fold: true
    html-math-method: katex
  docx: default
---

```{r setup, include=FALSE}
library(dplyr)
library(magrittr)
library(tidyverse)
library(stevemisc)
library(modelsummary)
#library(huxtable)
#library(kableExtra)
#library(stringr)
library(sentimentr)

knitr::opts_chunk$set(fig.width=2, fig.height=2)

```

He argues in response to Korsgaard that our self-constitutions are determined by our reflexive endorsements upon reflection of all the events in our past. This reflexive endorsement is determined by the emotions the agent expresses upon reflection on their own narrative. Therefore, his account is grounded in a more comprehensive description of how the agent goes about selecting narratives in a way that does not discard events.

As such Parfit's account still does not capture what we might think of as persons since it is difficult to determine what events are unique to a given person, and which are unique to some other prior material cause. Narrative explanations provide one account by explaining the relationship of cause and event in a way that preserves agency. Stories make our lives intelligible [@vell03] by providing motive and context to a collection of events and episodes.

First, music characterized as forms of artistic expression often get in the way of understanding love songs in the philosophical context. For one, we might worry about divergent ends [@gilm20]. Emotions directed at music are often oriented to ends such as pleasure and entertainment or commercial success. In other words, they are functional, meaning that they play some functional role and can be "type-identified" in virtue of this functional role. One aspect of this role, is that art forms such as those expressed by music, are used to create perceptions identified by us as representations of material or immaterial objects, the subjects of the focus of that perception.

For instance, we may think that self-subordination is largely defined by a narrative arc, what is sub-ordination in one context, is taking ownership of one's actions in another, taking responsibility over what one does, or did and what another may be tempted to do. This narrative arc gives meaning to a sequence of events the narrative is comprised of. What the events mean then, is largely determined by that narrative [@alts21, 2. Also see @sche96, 96]. But even this does not capture what we might think of as fully exercised agency. This form of thinking is not sufficient for the moral attributions of agency that we care about, for instance those that are expressed in our attributions of praise and blame, which regret more closely aligns to.

The concern here are expressions of agency. It is not clear whether regret is treated similarly for commercial music communities, or communities which do not have the economic capital to pursue intrinsic value goals through artistic expression. Consider one possible narrative for what counts as a necessary and sufficient condition for well-being as expressed in some popular songs. Namely, according to a given song, what counts as necessary for a person's life to go as well as possible? How should we recognize necessary and sufficient objects for a well-lived life, as expressed in a given song?

In other words, practical concerns get in the way of the lofty goal of the narrative self-constitution [@sche96b] of the agent. This would be a reason against ascribing psychological narratives to song lyrics. Either the expressed regret is important for planning according to some personal identity theories [@brat00; @vell03], or popular love songs are merely artistic expressions subject to socio-environment, and not narratively agentive. But we might think that this would be a reason against accepting the narrative view in general.

However, there is a conceptual difference between evaluating a given object, and perceiving that object. In an evaluation, I make a definitive judgement about the object of my perception. Watching a horror movie will cause me to experience fear, meaning I am evaluating something as deserving of fear. Though this leads to other questions, we might think that my response is purely one of perception in which there is no judgment. How an artist presents something, can be confused by me as either something deserving of evaluation, or merely a perception similar to viewing a rock lying on the path. Further, while an aesthetic experience may be based in perception, it is less clear where or how I should justify a given evaluation. In either case, this raises questions about our agency in ways perhaps answerable by a narrative view.

Discussions of commercial hip-hop music have often taken for granted that themes in hip-hop are either synonymous with issues of social justice [@rose94; @shus07], or misogyny [For instance see @kist10c; @ande03; @john95]. Further, it is an open and controversial question whether or not the values of the communities hip-hop are said to represent are in fact represented by hip-hip artists and their music [@shus07; @shus95b; @layb18]. Hip-hop's themes of social justice in hip-hop is often referenced as a response to historical and contemporary factors, such as mass incarceration, over / under policing, and the life expectancies of communities often associated with hip-hop. In cases such as these, hip-hop is important because of its social commentary [@nzin18a]. While it may be argued that the commercialized themes of misogyny undermine those of social justice, critics typically point out that what may appear to be misogynistic are likely critical word play. Instead, critics argue that the latter themes are either clever social commentaries in themselves, or that profit is the primary motivation for the latter themes. But rarely do these conversations consider the contexts in which certain responses make sense.

Moral psychology refers to our attempts to understand what is possible in regard to our behaviors, actions, and values. There are several questions, what kind of creatures are we, and which behaviors and values are available to us. Normative theory refers to our attempts to understand what our moral obligations are, which behaviors and actions are required of us. It assumes, in part, an understanding of who we are, and which behaviors and actions we are capable of. The way normative theory and moral psychology are compared then, is that when talking about moral obligation, one assumes that an individual only has an obligation when a required behavior is available to her. The other assumes that any good normative theory will only posit actions that are available to us. Narrative identity is a class of discussion within the study of moral psychology.

It provides some middle ground between moral psychology and normative theory. It also begins with two questions. The first is what we can do now to make future actions possible or impossible. The second asks whether we have an obligation now to make decisions that will make future actions possible or impossible. Following these questions, there are two categories of questions. One about our physical environments and how that environment makes possible, certain future actions. For example, consider Jill, the daughter of poor immigrants. Jill recognizes an obligation to give substantial amounts of wealth to charity. Therefore, Jill may have an obligation to pursue a high-compensation career.

## Narrative Planning

When we make plans for the future, we are often constrained in various ways. These ways may include facts about ourselves, we may not be tall enough to go on a given amusement park ride. Or have the necessary professional qualifications for a given job on the coast. Sometimes we are constrained by contingent facts about ourselves. These can include our personalities, our character traits, our emotional health and dispositions, or our abilities. Other times these constraints are external, such as past events. We can be permanently injured from a previous automobile accident. Inflation and the economy can prevent us from taking a vacation this year. We can be constrained by other people, as when someone rear-ends us and instead of driving to Yosemite, we have to get our car fixed. We can be constrained by the plans that others may have for themselves, and by extension, us; say in the case of marriage. Sometimes we are constrained by another's personal policies, for instance, because we do not profess religious faith, our friend's felt obligations to their religious parents may prevent them from accepting our marriage proposal.

Past experiences are connected to counterfactual thinking and regrets. The ways we reflect on these experiences and how we are constrained by them can sometimes lead to counterfactual thinking and regrets. We can regret the fact that our friend's parents do not think of us as a legitimate suitor.

There are times wherein these constraints, experiences and the regrets they lead to are real, occurring and constraining our choices in real-life. Goldie, however, argues that there are also times that while the constraints and regrets take place in real-life, the experience is make-believe or some other fictional event, what he calls non-local events. Non-local events are ones that take place in the past, future or make-believe, but both can be a part of a fiction. Both the real-life experiences, and the fictional ones are conveyed through narratives. A narrative is a representation of a sequence of events, whether actual, or make-believe. We can imagine someone telling us a fictional account of a purported historical event. Imagine that a friend, as a prank, calls you and tells you that he saw a random DUI check point on the way you normally take home from work and so you decide to take a different route. Through his fictional narrative, your friend has represented a sequence of events to you that constrained your choices.

We can represent both real-life and make-believe events through narrative and both can constrain our choices in real-life. More specifically, a narrative is the mental representation of a sequence of events. These can be a sequence of thoughts, thought through, and conceived of by both the narrator and the audience. The narrative can represent timelines which can be conscious or subconscious and they can provide coherence of the causal and other connections between events into what is called a narrative episode or episodes. We might imagine a counterfactual timeline wherein we wait in traffic over an hour, completely missing our dinner reservation and much needed time with our spouse. As such, these constraints can motivate feelings of regret, say that because of your alternate route, you are now late to dinner with your spouse.

What we can glean from these episodes are coherence, meaningfulness, and emotional importance/import. In imagining the counterfactual where we sit in traffic for over an hour, we may realize that we are really looking forward to having dinner with our spouse. We might realize that we have both been working really late and have not set enough time apart for each other. Goldie says that emplotment, is a psychological process which can be more or less successful. Emplotment occurs for those implicated in the narrative and those who engage with the narrative. Through emplotment, narratives give those who are implicated by them and those who engage with them, ways to consciously or subconsciously think about the events mentally represented by that narrative.

You consider how much time would be added to your commute if you went the way home that you normally would. The story your friend has told you, comes with some emotional baggage then. Realizing that you miss your spouse, you regret that you might miss your dinner reservation etc. This emotional baggage, and not the actual conditions, in part, is what determines the appropriateness of your response, whether you will take your usual way, or the other. Assuming you decide to avoid the fake DUI check-point, your response is emotionally appropriate because it is a response to how much you miss your spouse. Assuming that missing the dinner reservation equates to what most of us think of as a negatively valenced experience, taking the longer route would be the appropriate response in this situation. As such, this decision is emotionally important.

But when we think about this emotional import, the effect on our behavior may differ from the emotional import of a real-life but non-local event and a make-believe non-local event. This implies though, that the proper response to a situation is outlined by the emotional response to a given event whether true or make-believe. Especially because it seems that it is the narrative that outlines the proper emotional response and not real-life. Both narratives are non-local events, but one is real-life and the other make-believe. Our friend may say to us; "oh man, you don't wanna go that way let me tell you . . .", at which point he spins a yarn about his commute taking one and a half hours longer than it does normally and it is this yarn that motivated your counterfactual experiences and subsequent feelings of regret. As such

1. Narratives first seem to outline the proper emotional response to a given event.

But, then they are also,

2. Distinct from emotions that are an agent’s response to a given event or sequence of events. [See @gold09, 98]

The distinction then is between emotional import and emotional response. We ought to contrast these two features.

1. Emotional import is an integral part of the narrative

2. Emotional response is a response to the integral part of the narrative

We may have felt the fear in our friend's voice or seen the frustration on his face while he tells the story. If he is even somewhat adequate at doing so, it is us who feels the same frustration. We are transplanted into the story where as the character, we experience the apt emotions, but we can also experience emotions externally. The external emotions that we experience are not as necessary. Assuming that I am drawn into the narrative, I have one emotional experience, the one that is apt in the context. However, as an audience member, I can also have emotional experiences that are responses to my response in the story. I might read Anne Frank and I am drawn into her narrative experiencing the emotions that are apt in that context. However, as an external audience member, in response to the pain and fear that I feel internally, my external response is one of anger.

This can similarly occur in real-life personal narratives as well. We can imagine an office employee being humiliated at a team meeting by a senior member of the team and then recalling his humiliation later that evening, he responds emotionally with anger and rage. Here, the agent as character was humiliated by a more senior member at work and in the moment, all they could feel is humiliation, embarrassment, and shame. However, taking an external perspective on what happened, they “might conceive of what happened as deserving anger and resentment.”

By thinking through these narratives, we make the emotions appropriate in response to the narrative. This can occur with dramatic irony, the narrator is not aware of crucial facts about what happened until later and as such, the external emotion, the one in response to the internal emotion is different from the internal one.

## Conclusion

Counterfactual imagining occurs in the same way. When we imagine who we want to be, we may begin by thinking of what steps we can actively take to become that person. If we imagine ourselves to be financially independent, we may choose a college major in a field that promises a large salary. However, sometimes, once we set out on a path to becoming the person we desire, external constraints can reveal to us the feasibility of our goals. Upon entering university, we may have thought that we wanted a career in computer science but realizing how difficult the math is, we may think it is not worth it. Other factors can also constrain our choices.

There are two kinds of factors, positive and negative ones. A negative constraint is one wherein we pursue computer science but struggle with the math and decide we would rather study philosophy. A positive constraint however, is one wherein while we may be okay doing the math required by the CS field, it would detract too much from what we really liked about CS which is the analytic structure of argument. It turns out that what we liked in computer science was the logic and not so much the math. Therefore we switch majors to philosophy instead. This is an example of a positive constraint. We discover some additional desire that we have and this constrains our choice. We realize that we want to become a physician and do humanitarian work in an organization like doctors without boarders. We recognize that this will require many hours of study and does not promise a large salary. As such, it would leave us with very little time for romantic relationships and there is no financial compensation to justify the time away from loved ones. Therefore, we breakup with our college girlfriend. The positive constraint highlights an emerging goal or desire. This emerging goal or desire reveals new steps that we should take including breaking up with our girlfriend.

- Hypotheticals imperatives == oughts in light of stated goals

- When you fall short of these goals, you experience negative emotions.

- The negative emotions motivate counterfactual thinking, thinking back to the crucial moment that contributed to your failure to realize your goals

- Regret is an external emotion that arises in response to your decision underlying your goal failure

- Each, negative emotions, counterfactual narrative thinking, and regrets can have a feedback effect on one’s grasp of the related hypothetical imperatives, helping one to learn from one’s mistakes. Negative emotions then motivate counterfactual thinking.

The steps here being referenced are hypothetical imperatives, they are imperatives about what we should do given our stated goals. While hypothetical imperatives are implied by positive constraints, there is not initially a similar object with respect to negative constraints. For instance, we may think that negative constraints are associated not with *oughts*, but with *ought-nots*, but it is not clear.

# Works Cited

<!-- This option seems to be more pleasing for rmarkdown::pdf_document() with my templates -->
<!-- \setlength{\parskip}{6pt} -->

<!-- If you're using bookdown, this seems to look better with bookdown::pdf_document2() -->
\setlength{\parskip}{8pt}
\setlength{\parindent}{-0.15in}
\setlength{\leftskip}{0.15in}
\vspace*{-0.35in}
\noindent


