---
title: "True Love's Agency"
subtitle: "Narrative and Identity in Popular Music"
thanks: "Thanks to the ASA. **Current version**: `r format(Sys.time(), '%B %d, %Y')`; **Corresponding author**: montaque.reynolds@gmail.edu"
author:
- name: Montaque Reynolds
  affiliation: Saint Louis University
# bibliography: "`r paste0(Sys.getenv('HOME'),'/Dropbox/master.bib')`" # This would be more general
bibliography: /home/redapemusic35/data_storage/Un-Duplicates.bib
abstract: "With respect to personal identity, both Roman Altshuler and Christine Korsgaard argue we are defined by the stories we accept about ourselves. On Korsgaard's account, we select various events from our past and weave it into our own constructed narratives. For Altshuler, this account neglects the affect that some events have in the construction of our self-constitutions. He argues in response to Korsgaard that our self-constitutions are determined by our reflexive endorsements upon reflection of all the events in our past. This reflexive endorsement is determined by the emotions the agent expresses upon reflection on their own narrative. Therefore, his account is grounded in a more comprehensive description of how the agent goes about selecting narratives in a way that does not discard events. I argue that if this is what narrative in the psychological sense is, then we ought recognize them as a ubiquitous artifact in much of what we recognize as modern and popular artworks."
keywords: "Care Ethics, Aesthetics"
geometry: margin=1in
#mainfont: cochineal
#sansfont: Linux Biolinum O
fontsize: 11pt
endnote: no
always_allow_html: true
header_includes:
  - \usepackage{longtable}
  - \usepackage{hyperref}
  - \usepackage{setspace}
  - \usepackage{amsthm}
  - \usepackage{xurl}
format:
  pdf:
    geometry:
      - top=30mm
      - left=20mm
  html:
    code-fold: true
    html-math-method: katex
  docx: default
---

```{r setup, include=FALSE}
library(dplyr)
library(magrittr)
library(tidyverse)
library(stevemisc)
library(modelsummary)
#library(huxtable)
#library(kableExtra)
#library(stringr)
library(sentimentr)

knitr::opts_chunk$set(fig.width=2, fig.height=2)

```

# Personhood and Identity

Many popular songs are saturated in the emotion of regret.

*The Grand Tour*

> As you leave you'll see the nursery

> Oh, she left me without mercy

> Taking nothing but

> Our baby and my heart

and

*He Stopped Loving Her Today*

> He kept her picture on his wall

> Went half crazy now and then

> But he still loved her through it all

> Hoping she'd come back again

The above are emblematic country songs in that regret is commonly expressed in country music. Different songs express regret in different contexts however. *Apologize* by Timbaland is not a country song, and expresses regret in a different context. Here the narrator expresses regret for the love he *had* felt.

> You tell me that you need me

> Then you go and cut me down, but wait

> You tell me that you're sorry

> Didn't think I'd turn around and say

Love songs often express regret when a relationship ends. In the song *The Grand Tour*, the audience is being asked to imagine an offer to tour a large home "step right up, come on in". It is eventually made clear that while there are evidences as to whether the home is lived in, and by whom, these items are no longer in daily use "where she used to . . .". While the artifacts themselves speak to the fact that they were once shared by people who expressed positive sentiments towards one another, their current state suggests that they are no longer used this way ". . . this old house will never be the same . . .". In *The Grand Tour*, there is existing controversy over whether the end of the relationship is caused by the narrator, or the person no longer there. In the podcast *Cocaine and Rhinestones: The history of country music*, Tyler Mahan Coe suggests that the change in the state of the lives of the individuals involved in the story, is the result of a tragic mishap "There's her rings, all her things, and her clothes are in the closet" and "as you leave you'll see the nursery, . . . taking nothing but the baby and my heart".

While the events in *The Grand Tour* may not have been caused by the involvement from any agent, regret more often is tied to the involvement of some agent. In other words, the regret in *The Grand Tour* is likely caused by an event, whereas in other songs, it is likely caused by an action. In Jones' other song *He Stopped Loving Her Today*, the regret is more definitively caused by an action. "He said I'll love you 'till I die, She told him 'you'll forget in time'".

While in the two previous examples, regret is expressed upon the end of a relationship. In other examples, more positive emotions are expressed upon the dissolution of the relationship than of its continuation. For instance Kelly Clarkson's *Since U Been Gone* does this "Since you've been gone, I can breath for the first time . . .". There are also different reasons for the regret whether expressed for having suffered through the ordeal of that relationship, or for its end. Sometimes the regret is expressed as a longing for various qualities the loved possessed, for instance in the *Grand Tour*, "over there, sits the chair ... and whisper 'oh I love you'". This correlates with attributions of emotions associated with love, where love has often been defined as the feeling of loving emotions provoked in the lover by the loved. Upon the loved's absence, the lover no longer feels these emotions and experiences regret on account of their absence [@tayl76]. The lover can also experience regret in longing for the qualities not possessed by the loved, when someone whom they loved, failed to reciprocate in word or deed failed in some other way.

Narrative accounts of agency attempt to use the way an individual responds to such events, to identity the agent through space and time. According to some narrative accounts of agency, how we frame events such as these, is what makes the event meaningful [@sche96b, 96] for a given individual. Without narratives, the agency and the identity of the subject is lost among a causal chain among random events. This has been called 'constitution'. In terms of the constitution model of agency, the subject of a given event, without the binding effect a narrative, is victim to a disparate causal chain of cause and effect, our identity is merely an impersonal metaphysical continuation of matter [@kors96]. We are then merely a random collection of atoms.

In explaining the metaphysical continuity of an object across space and time as a person, how we ought to understand what we are, Derek @parf87 defends an account of *personal* identity. In order to understand what sort of object a person is, Parfit argues we need to understand two different qualities, the nature of a person, and their continued existence over time, what he calls the *criterion of identity*. But when we consider these qualities in contrast to persons versus non-persons, we must include not only physical states of matter, but also immaterial ones such as mental states, memories, beliefs, motivations, etc.

While Parfit's account does show how persons are not mere matter, causalists state that an action performed by an agent, is an event caused by the mental state of that agent [@alts21]. The difficulty arises in understanding how mental states are related to events, whether, emotional, causal or something else. Regardless of the relationship between mental states and the material universe, it is not clear where the causal chains originated. As such Parfit's account still does not capture what we might think of as persons. Narrative explanations provide one account by explaining the relationship of cause and event in a way that preserves agency. Stories make our lives intelligible [@vell03] by providing motive and context to a collection of events and episodes.

In other words, narrative offers an account of identity that is based on attributed meaning. The meanings that stories provide are not derived from the individual meanings of the events they represent however. Rather, the individual events derive their meaning from the overall meaning of the story. The outcome of the story determines the meaning of the events within the story. Why something happened is explained by the end of the story in which it happened. But this is ascribed by whoever that stakeholder happens to be. Causalists state that an action performed by an agent, is an event caused by the mental state of that agent [@alts21]. The difficulty arises in understanding how mental states are related to events, whether emotional, causal or something else.

Reductionists such as Parfit can define personal identity as the persistence of the human person over time, and say that this is reducible to the binding of psychological states with physical matter. Causlism is the most popular account that explains the origin of psychological states, an object *A* at time *T$_1$* is identical to object *B* at time *T$_2$* as long as we can draw a continuous line from object *A* at time *T$_1$* to object *B* at time *T$_2$*. The continuous line here is most often mental states such as memory, passions, character traits and dispositions. But often times it is the case that those memories we accept as definitive, have their origins in persons other than us. There are certain dispositions I have because of persons other than myself signing various documents articulating what rights I have for instance.

Christine @kors89 has argued that on @parf87's account of identity, a person is primarily a *locus of experience* [@kors89, 103]. This means that the way to identity an object as existing through space and time as it correlates with a person, is by identifying a set of experiences between objects across space and time and as are connected through a set of events. These events are psychological states and 'spatiotemporally continuous living body' [@kors89, 104]. In this way, it is plausible to draw a line from events in 1786 to my present day. In other words, because a person's psychological states have prior causes, the states themselves are merely some form of event and experience.

The divergence not only has implications for ways in which to identity identical objects persisting across space and time, but also with respect to moral attributions of praise and blame. For instance, Kantians and Utilitarians have differing conceptions of agency which together represent a source of justification for either view. Utilitarians too account for agency as a form of experience. When concerning moral obligation and duty for instance, it is the moral agent who deserves to be praised or blamed. In this way then, say my acceptance of a person's human rights has nothing to do with me. As such, the utilitarian asks 'what should be done for them?', persons with a characteristic form of experience. Since the Kantian asks 'what ought they do?', despite a given experience, Parfit's account does not account for what we all might think of as the exercise of agency. As such, Korsgaard goes on to argue that focusing on what an agent does, rather than their experiences, will lead to a drastically different concept of identity, grounded in a unique characterization of agency. One which she calls 'practical'. Her own account of agency and identity then, is practical.

Korsgaard then, defends a concept of narrative agency. Reductionist and causalist concepts of agency undermine our concepts of agency with regard to moral responsibility. These accounts fail to explain the attribution of praise or blame in response to an agent's actions. This is because they offer no way to define the line as beginning at *T$_1$* and ending at *T$_2$*, in other words, the object, that persistent thing deserving of either moral praise or blame, is indefinable. @kors89 proposes a practical conception of narrative identity. Accordingly, a person is an agent who uses narrative to define their own constitution. She calls this the *self*-constitution model of personal identity. As such, Korsgaard defends an account of personhood and identity grounded in narrative agency. On this account, we are defined by the stories we accept about ourselves. The act of acceptance
means that we select individual events from our pasts in order to construct a narrative that defines our identity.

Reductionism is one way to understand personal identity in the form of causal influences on agency, without reducing the agency. Here, human agency is explained by relating motives to events. Either psychological states like belief and desire are bound over time by psychological continuity, or an action is an event caused by mental states. Just how is the agency maintained in light of influential environmental effects on it?

The locus of the reduction is hard to pin down in the context of the kinds of desires expressed by an entity as complex as a human person. An analogous complexity can be found in many popular love songs. Although a murky concept, narratives offer a promising response to causal and psychological reductionism. This is because they can incorporate and give shape to "a wide range of heterogeneous" mental states and events [@alts21] in the same manner as psychological narratives. By giving shape to these factors, narrative theories explicate an agent's motivations as a response to environmental effects.

Narrative explanations provide one account by explaining the relationship of cause and event in a way that preserves agency. Stories make our lives intelligible [@vell03] by providing motive and context to a collection of events and episodes. In other words, narrative gives meaning to otherwise meaningless events. Overall, the meanings that stories provide are not derived from the individual meanings of the events they represent. Rather, the individual events derive their meaning from the overall meaning of the story. The outcome of the story determines the meaning of the events within the story. The meaning of the outcome is determined by the story teller. Why something happened is explained by the end of the story in which it happened.

Altshuler identifies a problem with this account, namely that it does not account for those events that are not selected by the agent. He argues that such events do have a causal effect on what ultimately constitutes one's personage, and as such Korsgaard's view is unable to provide the proper and necessary features of personhood. Following Peter @gold09, Altshuler instead identifies narrative with an agent's *ability* to reconfigure their motivational and psychological past with respect to their own reactions to these events. In other words, Altshuler too, defends a self-constitution model of agency and identity, but one on which a person's responses to his or her past, shape her future identity.

Altshuler responds to the reductionistic identity problem by expanding Korsgaard's analysis. On his account then, we are defined by the stories we accept about ourselves, which is determined by our reflexive rather than reflective endorsements. This reflexive endorsement is determined by emotions we express upon the agent's reflection on her own narrative. Since on Altshuler's account, it is possible for the agent to give an accounting for all of the experiences she has by the way of reflexive endorsement or rejection, this account does not disregard important agent forming experiences. Therefore, his account is grounded in a more comprehensive description of how the agent goes about selecting narratives in a way that does not discard events and encapsulates a holistic number of attributes in the constitution of an agent.

Although narrative offers promise, it is also not clear how we might recognize a narrative in the wild, what does a sample narrative look like? Focusing on the expressions of regret in some popular songs may provide one answer. If some songs are narratives, the expressions of regret in them, may provide a response to psychological and causal reductionism. Love songs or anti-love songs can express regret for when the relationship ends, or regret for the relationship not ending sooner; which is another way for thinking about how the narrator's life may have gone differently. What is important about the expression of the feeling of regret here, is what that experience does for the agent's behavior going forward in the context of the meaning that the narrative gives to that event, or the agent derives from it. Love songs could be a form of narrative thinking in both the philosophical context and the popular one. Importantly here however, love songs might be a process by which someone organizes their experience and creates their identity [@sche96b].

## Rap, Hip-Hop, and Other Popular Music Forms

It is possible that when a song expresses regret for not having met someone sooner, they are thinking about how their life might have gone had they married sooner. The marriage itself is not meaningful for the individual as a stand-alone event. Rather, the marriage only has causal influence on the subsequent events of that person's life and it is the person who defines the event in such a way to make it a meaningful marker of their own identity. It is where the marriage sits in the overall context of the course of a given relationship for instance. A marriage event in the context of a short and harmful relationship has a very different meaning than one in the context of a long and loving relationship. Most importantly however, it is important in the context of the meaning that a person derives from the event. The context of expressed regret best explains this.

Peter Goldie highlights our emotions as a form of reflection, especially that of regret. Sometimes as agents, the expressions of regret enables the further exercise of our agency. In these moments, the ability to tell a story becomes important as we are enabled by the narrative to recognize the appropriate objects of our emotions in the story. The narrator grew up surrounded by violence and poverty, is a descendant of slaves, did not have a male role model, but regret is either appropriate to aspects of the story which bear no direct relation to the narrator, or ones that do. More importantly however, being able to recognize and reflect on emotions enables one to express their agency going forward.

Michael @brat00 argues that as agents, we are purposeful and reflective about our motivations, and capable of organizing our activity over and in-line with our purposes and motivations as we reflect on them. One method of reflection involves the expressions of various emotions on the occurrence of some event.

> Goldie’s point is that it is the emotional structure of narrative that allows for this interaction of emotions: the confidence I feel in the narrative of my past, the shamefulness with which I present it to myself in the narrative, the regret I experience in envisioning it, the calm I attribute to myself in the future, and the satisfaction I feel in relation to it. This emotional structure is key to planning . . . [@alts21, 5].

In his paper *Narrative Thinking, Emotion, and Planning*, Peter Goldie provides a possible way to combine moral psychology and normative theory. He argues that narrative is substantial in our lives as it provides ways of thinking about how our lives may have gone differently, or may go differently and why; our plans for the future; and how things might turn out. Thinking in this way leads to regret if we are disappointed in a particular choice we have made. Our feelings of regret can cause us to behave differently in the future. In part then, questions about narrative thinking may be questions about moral agency.

Importantly, the possible prospect of being able to imagine today what a morally good life will look like for us tomorrow, is a question about how what we believe about ourselves today, including what desires we have, influence our ability to pursue these ways of being. Imagining what kind of person our spouse will be can perhaps open up some romantic possibilities while closing others. Imagining where we will buy our first home may restrict our career choices, just like imagining how many children we will have may affect where we want to live. We might imagine rearing our children on the same street we learned to ride a bike, and imagine taking our family three doors down to our parents' house for Sunday dinner. As such, we might decline graduate school and instead pursue a popular industry closer to where we went to middle school.

This concept of narrative thinking and planning is also important for goal formation. We can develop a sense of agency when what we imagine plays a role in the way things turn out for us. The image of ourselves performing a life-saving surgery on a patient may give us the extra motivation we need to to stay awake long hours in preparation for becoming a surgeon.

More importantly, we can develop a sense of agency when we imagine ways in which our friendships, family ties, and other important relationships will go. We can imagine the type of person we are to others and take needed steps for becoming that person. As such, the person we will be and how we will relate to others is the goal that is formed by a narrative. Consider one particular narrative, we imagine ourselves as thoughtful, kind, considerate, loving, or compassionate. Imagining ourselves this way becomes the motivation we need to read up on the latest parenting methods. We might imagine ourselves being invited to witness the birth of a friend's first child and scour the internet for advice on how to be a better gift giver. We might imagine ourselves handing a hot cup of tea to a friend who is facing an impeding divorce and read the latest books on divorce and counseling others through hard times.

While the argument that the way we imagine our lives going can have a positive causal effect on the kind of person we become, one may argue that this view is too optimistic. To what extent do the experiences we have, shape the person we become? For instance, Eric J. @mill20 argues that victimhood imposes normative standards that ground the moral status of the victim. What he means is that social roles, such as victim, determine the values we are expected to live by. As a victim, there are various normative standards imposed on us that undermine our ability to imagine other parenting styles and values, such as those relating to how we protect and nourish our children. Libertarian values may be those we are less apt to promote in our homes. One reason is that when victims as parents, or the parents of victims, instruct a child, they must instruct them to act in self-subordinating ways "when confronted by the police" [221] rather than in ways that assert their autonomy. While there is much that can be stressed on this point, what is important, is that a theory of narrative identity may attempt to absolve the tension by defining the agency of the would-be victim in some other way that does not involve victimhood. For instance, we may think that self-subordination is largely defined by a narrative arc, what is sub-ordination in one context, is taking ownership of one's actions in another, taking responsibility over what one does, or did and what another may be tempted to do. This narrative arc gives meaning to a sequence of events the narrative is comprised of. What the events mean then, is largely determined by that narrative [@alts21, 2. Also see @sche96, 96].

But even this form of thinking is not sufficient for the moral attributions of agency that we care about, for instance those that are expressed in our attributions of praise and blame. Consider the following example narratives:

* Ty Dolla’s *by Yourself*: “Stacked your bread and bought your own Mercedes (Vroom, vroom). You your own boss, do it your way (Way)

And contrast this with the possibility that while material goods may or may not be a necessary condition for well-being, they are certainly not a sufficient one as expressed in other popular songs. The protagonist in the song *Rich and Sad* by Post Malone, looks back over the events, motives, and desires that resulted in the dissolution of his relationship and he feels sadness, as an expression of regret:

* “All this stuntin' couldn't satisfy my soul (–oul), Got a hundred big places, but I'm still alone (–one)”.

First, music characterized as forms of artistic expression often get in the way of understanding love songs in the philosophical context. For one, we might worry about divergent ends [@gilm20]. Emotions directed at music are often oriented to ends such as pleasure and entertainment or commercial success. In other words, they are functional, meaning that they play some functional role and can be "type-identified" in virtue of this functional role. One aspect of this role, is that art forms such as those expressed by music, are used to create perceptions identified by us as representations of material or immaterial objects.

Our emotions then enable us to evaluate the object of which the music is a kind of representation. However, there is a conceptual difference between evaluating a given object, and perceiving that object. In an evaluation, I make a definitive judgement about the object of my perception. Watching a horror movie will cause me to experience fear, meaning I am evaluating something as deserving of fear. Though this leads to other questions, we might think that my response is purely one of perception in which there is no judgment. How an artist presents something, can be confused by me as either an evaluation or merely a perception. Further, while an aesthetic experience may be based in perception, it is less clear where or how I should justify a given evaluation. In either case, this raises questions about our agency in ways perhaps answerable by a narrative view.

But it does lead to another criticism, the agency of the artist versus that of the audience. Some music criticisms will often point out that musical taste assumes a sense of moral autonomy not available to some. If an artist is accustomed to abject poverty, then that person might be seen as vulnerable to market forces, creating art that is in high demand for the purposes of financial gain [@layb18], or only capable of representing their immediate physical environment [@rich02]. In other words, practical concerns get in the way of the lofty goal of the narrative self-constitution [@sche96b] of the agent. Regret within narratives are an example of such narrative agency. Either the expressed regret is important for planning according to some personal identity theories [@brat00; @vell03], or popular love songs are merely artistic expressions subject to socio-environment, and not narratively agentive.

The concern here are expressions of agency. It is not clear whether regret is treated similarly for commercial music communities, or communities which do not have the economic capital to pursue intrinsic value goals through artistic expression. Consider one possible narrative for what counts as a necessary and sufficient condition for well-being as expressed in some popular songs. Namely, according to a given song, what counts as necessary for a person's life to go as well as possible? How should we recognize necessary and sufficient objects for a well-lived life, as expressed in a given song?

There are two plausible stories here. First we might look at contemporary criticisms of popular rap and hip-hop music. For instance, that women who are exposed to negative consequences of infidelity in hip-hop and rap are more tolerant of a partner's infidelity than women exposed to positive consequences of infidelity [@alex21]. Or that men exposed to videos which sexually objectify women are more likely to adopt adversarial sexual beliefs, accept accounts of interpersonal violence the same way they do rape myths [@aubr11]; or that audiences who are exposed to violent media experienced more aggressive thoughts and feelings [@ande03; @john95].

What I mean by objects, are representations which are mimetic in nature. The common responses to such criticisms come in two forms. They typically make some causal claim about the effects of environment on both artistic performance [@rich02], and audience music selection criteria, for instance, that artists are merely defining their personal experiences [@shus07, 419]. This response will highlight unequal wealth opportunities among US social groups which would suggest the creation of environments of distrust and hopelessness and lower life expectancies which some rap and hip-hop songs are merely reporting on. The second kind of response makes a cultural claim deriving from supposed traditional practices in pre-colonial Africa [@abra06].

Importantly here, the responses that are grounded in assertions about the culture of pre-colonial Africa are not necessarily a response to the empirical claims about the representations of anti-social behavior in rap and hip-hop music, but rather to the metaphorical use of language exhibited by pre-colonial African tribal practices. What are commonly noted as anti-social themes in rap and hip-hop, then are downplayed as word-play underlying a cultural or political critique or something else entirely. Namely the references to violence and misogyny are allegorical, not literal [@smit97; @gate89]. What is important among these responses, is that they too undermine attributions of personal identity and human agency.

Separately, some have held that we can determine the values an artist holds, by carefully listening to the song lyrics they write. Although this fact would suggest that an artist's lyrics might qualify as a personal narrative defining an artist's identity and agency, it is not clear whether such narratives would qualify on this account of narrative identity. Although Altshuler's account could give more credence to music lyrics as an example narrative in the psychological sense, it is not clear how this may be the case. According to some accounts, an artist's written lyrics and musical arrangement merely express plausible values someone might hold [@malo18], while others articulate them as more definitive [@meis22a], still others argue that art is functional [@gilm20], thereby leaving open the possibility they could count as narrative in the functional sense, but do not do so necessarily.

Following Peter @gold09's 'emotion of regret' in the narrative identity literature, I attempt to explore a possible account of agency rooted in *lyrical* expressions of regret. Such expressions may serve to help artists and their audiences, discover what that artist, or the audience, cares most about, or to make themselves and their internal psychological states intelligible to a broader community of persons.

The criticism often found in philosophical reflections on these genres is also directed at the social conditions which are argued to give rise to the themes in hip-hop music, once again however, these fail to explain the agency of the characters within the genre as a narrative would. It may be that rap and hip-hop are not good example narratives. But they show promise. Consider the question above, is some material good a necessary and sufficient condition for well-being as expressed in some popular songs? As narratives, the two examples above would better explain why some event happened. Why the protagonist in *by yourself* severed her relationship with her significant other, and why the protagonist in *Rich and Sad* is rich and sad.

Here, we primarily contrast [money] as the material object expressing that it:

* “could satisfy my soul”

And contrasting this with [money] as the material object expressing that it:

* “could not satisfy my soul”.

One way that narratives are thought to explain agency then, is by synchronizing incongruous events, states, and motives. As such, a narrative can say yes, money is either a necessary and sufficient condition for well-being for some agent or not. As such, the expressions of regret offers a plausible way to recognize the core of one's agency.

Therefore, recognizing the source of some narratives may help to understand sources of identity. The various incidents and events have made it difficult for the agent to recognize value in non-material objects. The narrator grew up surrounded by violence and poverty, is a descendant of slaves, did not have a male role model, and therefore pinning for more abstract values would be unavailable to them. We can, and often do, ask a meta-ethical question about what kinds of objects are truly of moral value and why. The narrative provides us with a plausible account of the why. For instance, we can ask to what extent the quest for consumer goods ought to outweigh other pursuits such as time with one's children or calling one's mother on Sunday. What is probably missing from the above is the understanding that there is a difference between only some material possession being necessary for well-being, versus some non-material possession being necessary for well-being.

But exactly how are material and non-material objects expressed over and against one another other? It may be the case that volunteering at an orphanage is of moral value and it can be expressed in song in at least two ways. Lyrically, "I wish I had volunteered at the orphanage yesterday". Or lyrically that expresses a negative outcome for not having volunteered at the orphanage yesterday. In constructing lyrics of the second form, the author chooses words that either have been historically encoded with the sentiment she is hoping to ascribe to a state of affairs, or is potentially encoded with that sentiment in such a way that the desired emotion is potentially ascribed to that state of affairs. However, if I neglect my children in volunteering at an orphanage, then *my* volunteering is of reduced moral value and we could imagine a lyrics saying "I wish I had spent time with my children instead of volunteering at the orphanage yesterday", or that says "I spent so many hours at the orphanage that I do not know who my own children are anymore"; or "I spent hours at the orphanage, I do not know who my own children are anymore".

We can also express a normative question about what behaviors are appropriate, when we should be kind, or whether a given action is more kind than another using similar methods. But there are additional interesting questions. As inferred above, we ask about the context in which a given ethical question is of moral value, and we can express it as a value by inviting the audience to reflect on such expressions by coercing their emotions accordingly. Volunteering my time at an orphanage is of moral value, and so I would use music or poetry to evoke emotions in the audience that correspond with this value. Considering the context is a way to assess the rationality of a given question, emotional expression in art is a way to make sense of that question. Making sense of the question helps us to anticipate the answer in at least two ways, what does the artist suggest is valuable, we would then look at the emotional expressions in her art, and what is the agent potentially capable of valuing.

For instance, assuming that Jill is the last sentient creature on a far away planet, it may not make sense to ask what Jill's ethical obligations are to those around her. But contexts regarding ethical questions are important. There are two important such contexts here; socio-economic or cultural environments, and psychological or social ones. Given questions about morality, our concerns are largely about how we should behave toward others. For many years, this was answered by referencing cultural and socio-economic conditions. More controversially, it has also been answered by referencing psychological or social conditions. But this is not the same as asking whether a given question about ethical obligation makes sense or not. It would not make sense to say a person with a medical condition that precludes the experience of empathy, has an ethical obligation to experience the emotions that align with empathy. There is a way in which our questions about moral behavior should make sense. This is in the context of our behavior toward others. Most humans, will generally live in contexts wherein our behavior to others should have a kind of rationality about them, in valuing our relationships with others.

Discussions of commercial hip-hop music have often taken for granted that themes in hip-hop are either synonymous with issues of social justice [@rose94; @shus07], or misogyny [For instance see @kist10c; @ande03; @john95]. Further, it is an open and controversial question whether or not the values of the communities hip-hop are said to represent are in fact represented by hip-hip artists and their music [@shus07; @shus95b; @layb18]. Hip-hop's themes of social justice in hip-hop is often referenced as a response to historical and contemporary factors, such as mass incarceration, over / under policing, and the life expectancies of communities often associated with hip-hop. In cases such as these, hip-hop is important because of its social commentary [@nzin18a]. While it may be argued that the commercialized themes of misogyny undermine those of social justice, critics typically point out that what may appear to be misogynistic are likely critical word play. Instead, critics argue that the latter themes are either clever social commentaries in themselves, or that profit is the primary motivation for the latter themes. But rarely do these conversations consider the contexts in which certain responses make sense.

Moral psychology refers to our attempts to understand what is possible in regard to our behaviors, actions, and values. There are several questions, what kind of creatures are we, and which behaviors and values are available to us. Normative theory refers to our attempts to understand what our moral obligations are, which behaviors and actions are required of us. It assumes, in part, an understanding of who we are, and which behaviors and actions we are capable of. The way normative theory and moral psychology are compared then, is that when talking about moral obligation, one assumes that an individual only has an obligation when a required behavior is available to her. The other assumes that any good normative theory will only posit actions that are available to us. Narrative identity is a class of discussion within the study of moral psychology.

It provides some middle ground between moral psychology and normative theory. It also begins with two questions. The first is what we can do now to make future actions possible or impossible. The second asks whether we have an obligation now to make decisions that will make future actions possible or impossible. Following these questions, there are two categories of questions. One about our physical environments and how that environment makes possible, certain future actions. For example, consider Jill, the daughter of poor immigrants. Jill recognizes an obligation to give substantial amounts of wealth to charity. Therefore, Jill may have an obligation to pursue a high-compensation career.

The social version of this question is more opaque. It is a question about our social environments and to what extent our social environments can provide us with the resources necessary to fulfill our moral obligations. Once again, there are two categories of question here. For instance, consider our choices as to what kind of careers would make fulfilling our moral obligations possible. If we recognize a moral obligation to give vast amounts of wealth to charity, then we could pursue a set of social connections (work hard in high school and get into a good university) that would make our ability to fulfill this obligation more likely. The other category of question is even more difficult however. It begins as a question about ourselves and the sources of our beliefs as to what is possible, and what is not. We would start with a question about what is true about ourselves. Related to this is a question about what extent do those around us contribute to our beliefs about what is true about ourselves and what is obligatory in regard to our behavior. If we consider that we have a moral obligation to support national health, then there are some political parties we might campaign on behalf of and others we would not. Some philosophers have argued that how we should understand such questions is in the form of a narrative.

## Narrative Planning

When we make plans for the future, we are often constrained in various ways. These ways may include facts about ourselves, we may not be tall enough to go on a given amusement park ride. Or have the necessary professional qualifications for a given job on the coast. Sometimes we are constrained by contingent facts about ourselves. These can include our personalities, our character traits, our emotional health and dispositions, or our abilities. Other times these constraints are external, such as past events. We can be permanently injured from a previous automobile accident. Inflation and the economy can prevent us from taking a vacation this year. We can be constrained by other people, as when someone rear-ends us and instead of driving to Yosemite, we have to get our car fixed. We can be constrained by the plans that others may have for themselves, and by extension, us; say in the case of marriage. Sometimes we are constrained by another's personal policies, for instance, because we do not profess religious faith, our friend's felt obligations to their religious parents may prevent them from accepting our marriage proposal.

Past experiences are connected to counterfactual thinking and regrets. The ways we reflect on these experiences and how we are constrained by them can sometimes lead to counterfactual thinking and regrets. We can regret the fact that our friend's parents do not think of us as a legitimate suitor.

There are times wherein these constraints, experiences and the regrets they lead to are real, occurring and constraining our choices in real-life. Goldie, however, argues that there are also times that while the constraints and regrets take place in real-life, the experience is make-believe or some other fictional event, what he calls non-local events. Non-local events are ones that take place in the past, future or make-believe, but both can be a part of a fiction. Both the real-life experiences, and the fictional ones are conveyed through narratives. A narrative is a representation of a sequence of events, whether actual, or make-believe. We can imagine someone telling us a fictional account of a purported historical event. Imagine that a friend, as a prank, calls you and tells you that he saw a random DUI check point on the way you normally take home from work and so you decide to take a different route. Through his fictional narrative, your friend has represented a sequence of events to you that constrained your choices.

We can represent both real-life and make-believe events through narrative and both can constrain our choices in real-life. More specifically, a narrative is the mental representation of a sequence of events. These can be a sequence of thoughts, thought through, and conceived of by both the narrator and the audience. The narrative can represent timelines which can be conscious or subconscious and they can provide coherence of the causal and other connections between events into what is called a narrative episode or episodes. We might imagine a counterfactual timeline wherein we wait in traffic over an hour, completely missing our dinner reservation and much needed time with our spouse. As such, these constraints can motivate feelings of regret, say that because of your alternate route, you are now late to dinner with your spouse.

What we can glean from these episodes are coherence, meaningfulness, and emotional importance/import. In imagining the counterfactual where we sit in traffic for over an hour, we may realize that we are really looking forward to having dinner with our spouse. We might realize that we have both been working really late and have not set enough time apart for each other. Goldie says that emplotment, is a psychological process which can be more or less successful. Emplotment occurs for those implicated in the narrative and those who engage with the narrative. Through emplotment, narratives give those who are implicated by them and those who engage with them, ways to consciously or subconsciously think about the events mentally represented by that narrative.

You consider how much time would be added to your commute if you went the way home that you normally would. The story your friend has told you, comes with some emotional baggage then. Realizing that you miss your spouse, you regret that you might miss your dinner reservation etc. This emotional baggage, and not the actual conditions, in part, is what determines the appropriateness of your response, whether you will take your usual way, or the other. Assuming you decide to avoid the fake DUI check-point, your response is emotionally appropriate because it is a response to how much you miss your spouse. Assuming that missing the dinner reservation equates to what most of us think of as a negatively valenced experience, taking the longer route would be the appropriate response in this situation. As such, this decision is emotionally important.

But when we think about this emotional import, the effect on our behavior may differ from the emotional import of a real-life but non-local event and a make-believe non-local event. This implies though, that the proper response to a situation is outlined by the emotional response to a given event whether true or make-believe. Especially because it seems that it is the narrative that outlines the proper emotional response and not real-life. Both narratives are non-local events, but one is real-life and the other make-believe. Our friend may say to us; "oh man, you don't wanna go that way let me tell you . . .", at which point he spins a yarn about his commute taking one and a half hours longer than it does normally and it is this yarn that motivated your counterfactual experiences and subsequent feelings of regret. As such

1. Narratives first seem to outline the proper emotional response to a given event.

But, then they are also,

2. Distinct from emotions that are an agent’s response to a given event or sequence of events. [See @gold09, 98]

The distinction then is between emotional import and emotional response. We ought to contrast these two features.

1. Emotional import is an integral part of the narrative

2. Emotional response is a response to the integral part of the narrative

We may have felt the fear in our friend's voice or seen the frustration on his face while he tells the story. If he is even somewhat adequate at doing so, it is us who feels the same frustration. We are transplanted into the story where as the character, we experience the apt emotions, but we can also experience emotions externally. The external emotions that we experience are not as necessary. Assuming that I am drawn into the narrative, I have one emotional experience, the one that is apt in the context. However, as an audience member, I can also have emotional experiences that are responses to my response in the story. I might read Anne Frank and I am drawn into her narrative experiencing the emotions that are apt in that context. However, as an external audience member, in response to the pain and fear that I feel internally, my external response is one of anger.

This can similarly occur in real-life personal narratives as well. We can imagine an office employee being humiliated at a team meeting by a senior member of the team and then recalling his humiliation later that evening, he responds emotionally with anger and rage. Here, the agent as character was humiliated by a more senior member at work and in the moment, all they could feel is humiliation, embarrassment, and shame. However, taking an external perspective on what happened, they “might conceive of what happened as deserving anger and resentment.”

By thinking through these narratives, we make the emotions appropriate in response to the narrative. This can occur with dramatic irony, the narrator is not aware of crucial facts about what happened until later and as such, the external emotion, the one in response to the internal emotion is different from the internal one.

## Conclusion

Counterfactual imagining occurs in the same way. When we imagine who we want to be, we may begin by thinking of what steps we can actively take to become that person. If we imagine ourselves to be financially independent, we may choose a college major in a field that promises a large salary. However, sometimes, once we set out on a path to becoming the person we desire, external constraints can reveal to us the feasibility of our goals. Upon entering university, we may have thought that we wanted a career in computer science but realizing how difficult the math is, we may think it is not worth it. Other factors can also constrain our choices.

There are two kinds of factors, positive and negative ones. A negative constraint is one wherein we pursue computer science but struggle with the math and decide we would rather study philosophy. A positive constraint however, is one wherein while we may be okay doing the math required by the CS field, it would detract too much from what we really liked about CS which is the analytic structure of argument. It turns out that what we liked in computer science was the logic and not so much the math. Therefore we switch majors to philosophy instead. This is an example of a positive constraint. We discover some additional desire that we have and this constrains our choice. We realize that we want to become a physician and do humanitarian work in an organization like doctors without boarders. We recognize that this will require many hours of study and does not promise a large salary. As such, it would leave us with very little time for romantic relationships and there is no financial compensation to justify the time away from loved ones. Therefore, we breakup with our college girlfriend. The positive constraint highlights an emerging goal or desire. This emerging goal or desire reveals new steps that we should take including breaking up with our girlfriend.

- Hypotheticals imperatives == oughts in light of stated goals

- When you fall short of these goals, you experience negative emotions.

- The negative emotions motivate counterfactual thinking, thinking back to the crucial moment that contributed to your failure to realize your goals

- Regret is an external emotion that arises in response to your decision underlying your goal failure

- Each, negative emotions, counterfactual narrative thinking, and regrets can have a feedback effect on one’s grasp of the related hypothetical imperatives, helping one to learn from one’s mistakes. Negative emotions then motivate counterfactual thinking.

The steps here being referenced are hypothetical imperatives, they are imperatives about what we should do given our stated goals. While hypothetical imperatives are implied by positive constraints, there is not initially a similar object with respect to negative constraints. For instance, we may think that negative constraints are associated not with *oughts*, but with *ought-nots*, but it is not clear.

# Works Cited

<!-- This option seems to be more pleasing for rmarkdown::pdf_document() with my templates -->
<!-- \setlength{\parskip}{6pt} -->

<!-- If you're using bookdown, this seems to look better with bookdown::pdf_document2() -->
\setlength{\parskip}{8pt}
\setlength{\parindent}{-0.15in}
\setlength{\leftskip}{0.15in}
\vspace*{-0.35in}
\noindent


