
---
title: "The Moral Privilege of Writing a Love Song-Outline"
thanks: "Thanks to the ASA. **Current version**: `r format(Sys.time(), '%B %d, %Y')`; **Corresponding author**: montaque.reynolds@gmail.edu"
author:
- name: Montaque Reynolds
  affiliation: Saint Louis University
# bibliography: "`r paste0(Sys.getenv('HOME'),'/Dropbox/master.bib')`" # This would be more general
bibliography: /home/redapemusic35/data_storage/Un-Duplicates.bib
abstract: "In this paper, I articulate the importance of writing love songs for marginalized groups. According to narrative theories of agency, narrative thinking is substantial in our lives as it provides ways of thinking about how our lives may have gone differently, and how our lives may go differently. However, some may argue that this view assumes a sense of moral autonomy not available to some social classes, for instance victims of racism and other forms of societal marginalization. As a moral technology, I argue that alternative narratives in music can define a plausible alternative agency for such groups. I look at two classes of music, Christian Hip-Hop and popular Hip-Hip and argue that one includes plausible future plans as these refer to, most notably, the plans we have regarding ourselves and our relationships to others. In other words, narratives in music sometimes is a study of the possible core values of the members of a musical community as these are related to interpersonal correspondance. These considerations provide a novel way of thinking about how our lives may go differently and how narratives in entertainment may promote these alternative ways of thinking."
keywords: "Care Ethics, Aesthetics"
geometry: margin=1in
#mainfont: cochineal
#sansfont: Linux Biolinum O
fontsize: 11pt
endnote: no
always_allow_html: true
header_includes:
  - \usepackage{longtable}
  - \usepackage{hyperref}
  - \usepackage{setspace}
  - \usepackage{amsthm}
  - \usepackage{xurl}
---

```{r setup, include=FALSE}
library(dplyr)
library(magrittr)
library(tidyverse)
library(stevemisc)
library(modelsummary)
#library(huxtable)
#library(kableExtra)
#library(stringr)
library(sentimentr)

knitr::opts_chunk$set(fig.width=2, fig.height=2)

```

Consider one possible narrative for what counts as a necessary and sufficient condition for well-being as expressed in some popular songs. For instance, we can contrast the following two stories:

* Ty Dolla’s *by Yourself*: “Stacked your bread and bought your own Mercedes (Vroom, vroom). You your own boss, do it your way (Way)

And contrast this with the possibility that material goods are not a necessary and sufficient condition for well-being as expressed in other popular songs:

* Post Malone’s *Rich and Sad*: “All this stuntin' couldn't satisfy my soul (–oul), Got a hundred big places, but I'm still alone (–one)”.

There are two plausible stories here. First we might look at contemporary criticisms of popular rap and hip-hop music. For instance, that women who are exposed to negative consequences of infidelity in hip-hop and rap are more tolerant of a partner's infidelity than women exposed to positive consequences of infidelity [@alex21]. Or that men exposed to videos which sexually objectify women are more likely to adopt adversarial sexual beliefs, accept interpersonal violence and rape myths [@aubr11]; and that audiences who are exposed to violent media experienced more aggressive thoughts and feelings [@ande03; @john95].

The common responses to such criticisms come in two forms. They typically make some causal claim about the effects of environment on both artistic performance, and audience music selection criteria, or make a cultural claim deriving from supposed traditional practices in pre-colonial Africa. Importantly here, the responses that are grounded in assertions about the culture of pre-colonial Africa are not necessarily a response to the empirical claims about the representations of anti-social behavior in rap and hip-hop music.
