---
title: Moral Privilege
authors:
  - name: Norah Jones
    affiliation: The University
    roles: writing
    corresponding: true
bibliography: references.bib
---

# Art Interpretive Injustice

> In its general form, an art-interpretive injustice is one in which an agent is wronged in their creative capacity as a possible artist. The primary injustice here concerns the failure to attribute art concepts to a person's work because of their identity.

But the injustice occurs when some concepts are attributed while others are not. In the question regarding black country music, the injustice occurs when certain concepts common to a genre are cause for exclusion because of the identity prejudice in the "collective hermeneutical" resource. For instance, when values, not form, often associated with a given genre are the reason for denying an artist inclusion into that genre. Following Malone,

> This wrongs them in a distinct capacity essential to human value, so it is a different kind of injustice.

A common example of this form of injustice *does not* include the prosecutorial use of rap music as example of injustice. What is at issue here however, is the ability to define the relationship between genre discourse and identity prejudice.

# Prosecutorial use of rap music as example of injustice

1. Rap on trial mentality: “rap music, unlike any other musical genre, somehow reflects the
true thoughts, beliefs, and character of the person performing it” (Nielson and Dennis, 2019, 79).
   1. Medina trial
   2. Lack of similar responses to 'Gun's and Roses' *Used to Love Her, but Had to Kill Her* (1988)
2. To be clear, we are talking about an artform that is 'coded' as black: "involves black artists and a genre which is coded as black, but given this coding, the prejudice against rap can spill over to non-black rappers"
3. The reason it is art interpretive injustice is because "In cases like Medina’s, the rapper is either not deemed to have produced a work of art at all or deemed presumptively to have produced art which is confessional."
   1. Not confessional
   2. Not a work of art
      1. Not employing artistic license

# Epistemic Injustice

## Testimonial and Hermeneutical Injustice

1. Testimonial Injustice: "listeners extend the wrong degree of credibility"
   1. Testimony of the speaker is called into question because of the identity of the speaker
   2. But the victim in the Medina case does not suffer from credibility deficit because his lyrics were used as credible evidence
   3. However, the victim's lyrics were taken as testimony rather than artistic expression
2. Hermeneutical Injustice: "when someone's own experience is obscurred because the available concepts distort it or render it inscrutable"
   1. Social experiences "obscured from collective understanding"
   2. This is caused by structural identity prejudice in the "collective hermeneutical" resource
   3. Analogous to the Medina case, the prosecuters misdescribe the victim's experience (Fricker 2016, 167).

## Some other forms of epistemic injustice

1. Interpretive Injustice
2. Discursive Injusitice
3. Aesthetic Injustice

# What they have in common

> identity prejudice and the matter at issue is the application of shared art concepts.

1. Artistic injustice is the failure to attribute art concepts to a person's work because of their identity
2. This is important in the conversation of black country music. But here, the injustice occurs when certain concepts common to a genre are the cause of the identity prejudice in the "collective hermeneutical" resource
3. For instance, when values often associated with a given genre are the reason for denying an artist inclusion into that genre.
